### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by stinor** [OrebroUniversity/yumi#15]
Hi

I have tried to build this following the instructions provided but it fails with the following error

CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "abb_egm_interface"
  with any of the following names:

    abb_egm_interfaceConfig.cmake
    abb_egm_interface-config.cmake

I have not been able to find anything related to these in the repository.

Cheers

**Comment by tstoyanov** [comment]
Hi,

sorry about that. We are working on some new features which got pushed prematurely into master. I have reverted the merge and you should be able to build now. Can you please check if you are able to build now?

**Comment by stinor** [comment]
Hi

Many thanks. I am now able to do a build so will close this issue.
