### ISSUE TITLE
How can I use ros_control interface(and naive RAPID) together with moveit( its planner and execution)?I was confused actually, Thanks.

### ISSUE THREAD

**Issue by JJHu1993** [OrebroUniversity/yumi#31]
How can I use ros_control interface(and naive RAPID) together with moveit( its planner and execution)? Thanks , I was confused actually.

**Comment by YoshuaNava** [comment]
Hey,
First of all you need to load the RAPID modules into YuMi. Check [this guide](https://github.com/kth-ros-pkg/yumi/wiki/Firmware)

Then, you'll have to connect your robot to your PC, and setup a LAN. [Network setup](https://github.com/kth-ros-pkg/yumi/wiki/Network-setup)

To control the robot by means of ROS controllers, launch the [live robot nodes](https://github.com/kth-ros-pkg/yumi/wiki/Live-robot)

Finally, if you want to use a planner, as a start I recommend using [MoveIt!](https://github.com/kth-ros-pkg/yumi/wiki/MoveIt%21)


Please let me know if this helps,

Yoshua
