### ISSUE TITLE
- Portability on ROS1 Noetic.

### ISSUE THREAD

**Issue by giordy-sudo** [OrebroUniversity/yumi#36]
Hello, I have some issues when I compile (catkin build) this package :

- **yumi_hw**.

In particular error is :
![yumi_hw_1](https://user-images.githubusercontent.com/66011580/146350721-3362512e-620b-4a10-8d49-0361704b7402.png)
![yumi_hw_2](https://user-images.githubusercontent.com/66011580/146350728-71fa36a9-623a-4448-a7ee-fac7b950149e.png)

Thanks a lot.

**Comment by tstoyanov** [comment]
Hi,

this repository is deprecated. Check https://github.com/ros-industrial/abb_robot_driver for the new yumi drivers.
