### ISSUE TITLE
yumi_hw/rapid/ros_control

### ISSUE THREAD

**Issue by juliamp22** [OrebroUniversity/yumi#9]
Hi,
I would like to know if ROS_motionServer file on yumi_hw is available or is going to be available. Now  I am usig yumi_support/rapid/ROS_motionServer file, but it Works with joint_traj_msg, different as msg_joint_data.

If not, I will modify the actual ROS_motionServer file in yumi_support directory.

Thanks for all,

Júlia

**Comment by tstoyanov** [comment]
Hi Julia,

when using yumi with a ros_control interface we had to do things a little bit differently from the legacy MoveIt interface. The legacy interface requires one state server and one motion server for each arm. The ros control interface only uses one state server for both arms. This is done in a tight loop with the corresponding hardware interface driver: we send the current joint states from RAPID to the interface node and then block and wait for the interface node to send us back the next joint commands. Unlike the legacy interface, we don't support trajectory download. The robot is at all times controlled by the ros_control node and requires constant commands.

To make this work, also note that you need to download our fork of industrial_core, as there is a small but very necessary change in the number of joints we are communicating between the nodes. 

Hope that helps.
Todor
